### ISSUE TITLE
[BUG] Java 无法调用 SimpleConfigAPI

### ISSUE THREAD

**Issue by SmallasWater** [WetABQ/EasyAPI-Nukkit#9]
使用 SimpleConfigAPI 的时候编译器报错
![image](https://user-images.githubusercontent.com/46156675/76958842-62dbde80-6953-11ea-8dd4-efca997d9fbd.png)
![image](https://user-images.githubusercontent.com/46156675/76958976-a2a2c600-6953-11ea-950f-983f6f8da4b4.png)

EasyAPI依赖库已安装

**Comment by WetABQ** [comment]
java8 keywords

fixed
